### ISSUE TITLE
cannot create signed application

### ISSUE THREAD

**Issue by marcusb** [jvoegele/gradle-android-plugin#10] opened 2010-11-29 16:23 UTC
The plugin cannot create signed application archives. It tries to sign the file specified by  'out.unsigned.package', but nothing creates this file.

**Comment by fdasoghe** [comment] 2010-11-30 14:44
Did you call the androidPackageRelease?
Or better, can you post your build.gradle file and the command you issue?

**Comment by marcusb** [comment] 2010-11-30 20:13
Hmm, seems I made a mistake. Sorry about that.

**Comment by fdasoghe** [comment] 2010-11-30 21:31
Hello.
It seems I'm having your same issue.
Calling task "androidPackageRelease" doesn't create the 'out.unsigned.package'.
For what I see, the reason is that both androidPackageDebug and androidPackageRelease call the apkbuilder ant command, but this (in ApkBuilderTask_r7) create always the output file in out.debug.unaligned.package...

**Comment by marcusb** [comment] 2010-12-01 05:45
Yes, this issue is valid after all. Please reopen.

**Comment by fdasoghe** [comment] 2010-12-01 11:05
I think the only one who can reopen the issue is Jason...

Anyway, I think this issue is of broader importance than "only" the creation of release package. For example, it's also related to issue #6 about input and output files (I'm going to write more there).

**Comment by jvoegele** [comment] 2010-12-04 13:16
I've reopened this issue for investigation.

**Comment by jvoegele** [comment] 2010-12-04 13:40
I think this has been fixed by think01 in his fork.  I'll get confirmation and apply when he says it's ready.

**Comment by fdasoghe** [comment] 2010-12-22 14:43
Fixed in 0.9.5. See the README.txt for instructions.

**Closed as completed by fdasoghe** 2010-12-22 14:43 UTC
