### ISSUE TITLE
Gradle Android Plugin does not work with r20

### ISSUE THREAD

**Issue by ealden** [jvoegele/gradle-android-plugin#65] opened 2012-07-03 08:39 UTC
r20 was just released, and it causes `developerBuild` to fail.

A quick check says that `com.android.ant.NewSetupTask` could not be found.  When I did a compare with `$ANDROID_HOME/tools/ant/build.xml` in R18 and R20, the latter no longer defines a custom `taskdef` with the name "setup".

It looks like we need to revalidate the build.xml and see how we can apply it to this plugin.

**Comment by dvermaasen** [comment] 2012-07-26 14:05
I am not that deep inside your work, but i was trying to get the plugin running this morning and i had a couple of problems.
First the mentioned missing <code>com.android.ant.NewSetupTask</code>. 
I know, it is a workaround, but you can just replace the anttasks.jar with another one containing the missing files, it works for the moment (at least in my case).

Another problem is caused by the file <code>$ANDROID_HOME/tools/source.properties.</code> It looks like in the previous version the <code>Pkg.Revision</code> was always set to a non-decimal number. With SDK 20.0.1 it receives a new format including minor releases and bugfixes, which causes a NumberFormatException. To prevent this, just set the Revision to "20".

**Comment by ghost** [comment] 2012-08-10 08:13
I was trying to build a simple android application and using sdk 20. and try to replace the anttasks.jar as a workaround fo r20. i get an exception :

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':androidPackage'.
  > apkbuilder doesn't support the "signed" attribute

**Comment by dvermaasen** [comment] 2012-08-14 10:25
post the stacktrace to provide more informations. Execute the task with --stacktrace param like that:
<code>gradle task --stacktrace</code>

**Comment by MarcinGil** [comment] 2012-08-24 10:50
I'm wondering why maven plugins have no such problems..

**Comment by dhesse1** [comment] 2012-08-27 15:00
I have a NumberFormatException with R 20.0.3

Caused by: java.lang.NumberFormatException: For input string: "20.0.3"
    at java_lang_Integer$parseInt.call(Unknown Source)
    at com.jvoegele.gradle.plugins.android.AndroidSetupFactory.getAndroidSdkToolsRevision(AndroidSetupFactory.groovy:38)
    at com.jvoegele.gradle.plugins.android.AndroidSetupFactory.getAndroidSetup(AndroidSetupFactory.groovy:45)
    at com.jvoegele.gradle.plugins.android.AndroidPlugin.androidSetup(AndroidPlugin.groovy:89)
    at com.jvoegele.gradle.plugins.android.AndroidPlugin.apply(AndroidPlugin.groovy:77)
    at com.jvoegele.gradle.plugins.android.AndroidPlugin.apply(AndroidPlugin.groovy)
    at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.providePlugin(DefaultProjectsPluginContainer.java:107)
    at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.addPluginInternal(DefaultProjectsPluginContainer.java:71)
    at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.apply(DefaultProjectsPluginContainer.java:37)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:101)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:32)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:72)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:114)
    at org.gradle.api.internal.project.AbstractProject.apply(AbstractProject.java:841)
    at org.gradle.api.Project$apply.call(Unknown Source)
    at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
    at org.gradle.api.Script$apply.callCurrent(Unknown Source)
    at build_1531oj677oreddr55l139bb95q.run(/Users/..../build.gradle:10)
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
    ... 33 more

The String apperas to be the same as here: http://developer.android.com/tools/sdk/tools-notes.html#notes

**Comment by dvermaasen** [comment] 2012-08-28 07:01
> Another problem is caused by the file $ANDROID_HOME/tools/source.properties. It looks like in the previous version the  Pkg.Revision was always set to a non-decimal number. With SDK 20.0.1 it receives a new format including minor releases and bugfixes, which causes a NumberFormatException. To prevent this, just set the Revision to "20".

**Comment by forgemo** [comment] 2012-09-01 22:20
This issue has been resolved in the latest 1.2.0-SNAPSHOT (It works at least for me).

**Closed as completed** 2012-09-25 15:03 UTC
Labels: bug
