### ISSUE TITLE
Resources from external JARs not packaged correctly

### ISSUE THREAD

**Issue by ckesselh** [jvoegele/gradle-android-plugin#42] opened 2012-01-02 20:35 UTC
Hi there,

I'm fairly new to both Android and Gradle, so please bear with me. 

I've recently run into some trouble when using Gradle to build my Clojure-based Android applications. As it turns out, the root cause of this lay with the Gradle Android plugin itself: Unlike e.g. its default Ant or Maven counterpart, it currently doesn't seem to configure the underlying Ant tasks properly so that non-Java resource (e.g. property) files are also included in the final APK (as well as its manifest). When using a library that (for one reason or the other) depends on those resources to be there at run-time, that turns out a problem.

I see a number of possible solutions:

1) Instruct the ApkBuilder task to simply Include all non-Java resources from all external (i.e. runtime) dependency JARs building the APK. This is more or less what the basic Android Ant set-up or the equivalent Maven plugin does by default. For now, I've created myself some small patch to the Gradle Android plugin that does just this, you can find it here: https://github.com/ckesselh/gradle-android-plugin/commit/e41d8ccd585885cf705f8df887decf578c6a9acb . Obvious disadvantage: The user has no straightforward way to manually exclude/include any JARs on a per-project basis.
2) Add a new configuration (e.g. "android") as a parent to "runtime" that could then be used by the user to manually list those dependencies for which non-Java resources should be included. This would be somewhat similar to the "gwt" configuration used in scope of the Gradle GWT plugin, I guess. 
3) Add some other configuration parameter that would allow the user to somehow influence the process.

I'm willing to hand-in a pull request with the necessary changes myself (in good time); what I'm currently looking for is some sound advice on what would actually be the best way to proceed (see options above).

Any ideas?

Regards,

Chris

**Comment by fdasoghe** [comment] 2012-01-03 09:19
Hello.

Assuming you're using the latest release (1.1.0) from Maven Central, I have
a question.

Is your problem related to external JARs or some other resource files? If I
remember well, they are managed differently from
Gradle/Android/gradle-android-plugin.

Anyway, I have an Android project with both external JARs and resource
files and it works like a charm, so I'm confident there is some little
trouble with your build configuration that can be fixed quickly.

For example, if you have resource files, they must be put in
src/main/resources, are they?

Cheers,

Fabio

2012/1/2 Christian Kesselheim <
reply@reply.github.com

**Comment by ckesselh** [comment] 2012-01-03 09:35
Sorry for not making that clear. My problem's about resource files that come bundled WITHIN an external JAR (e.g. clojure-1.3.jar ships with a version.properties, which Clojure then tries to read and use at run-time). Project-specific resources (i.e. src/main/resources) on the other hand seem to work just fine.

If you check the default Android build.xml or even the corresponding Maven plugin, you'll see that there the external JAR's own resources are automatically listed in the manifest and embedded in the APK itself at the time of build. For the Gradle Android plugin, this is not yet the case, causing problems with libraries such as Clojure that rely on their embedded resources to be there at run-time (hence this issue). 

Of course, as a workaround, I could now also just manually extract all non-JAVA resources from clojure-1.3.jar  and place them into the project's src/main/resources, but then I would have to repeat that very process each time a new version of Clojure gets released.

**Comment by fdasoghe** [comment] 2012-01-03 17:54
I see. Of course this issue has to be resolved. I still don't understand why the application code is not able to "see" the resource file from an included JAR. Shouldn't it be sufficient to include the JAR into the final APK?

**Comment by ckesselh** [comment] 2012-01-03 21:47
Its because the similarities between standard J2EE (super-)packages such as JAR, EAR or WAR and the Android equivalent (APK) ends with the fact that both are valid ZIP files, possibly containing an optional META-INF folder. 

For example, instead of JAVA bytecode being packaged as individual .class files, those APK packages simply contain a single binary DEX file with all the equivalent Dalvik (not JAVA!) bytecode linked-in. Also, there is no concept of a simple, embedded JAR file within that main archive (Android has its own concept of "libraries", which is not quite the same).

To illustrate the particular problem I've tried to bring-up here, this is a minimal APK file of the project located here (https://github.com/ckesselh/helloandroid/tree/gradle) that has been built using the vanilla version of the Gradle Android plugin available from Maven central:

```
ckesselh$ jar tvf build/distributions/helloandroid-1.0.0.apk 
   335 Tue Jan 03 22:29:14 CET 2012 META-INF/MANIFEST.MF
   456 Tue Jan 03 22:29:14 CET 2012 META-INF/ANDROIDD.SF
   776 Tue Jan 03 22:29:14 CET 2012 META-INF/ANDROIDD.RSA
   956 Tue Jan 03 22:29:12 CET 2012 res/layout/main.xml
  1268 Tue Jan 03 22:29:12 CET 2012 AndroidManifest.xml
  1012 Tue Jan 03 22:29:12 CET 2012 resources.arsc
3391652 Tue Jan 03 22:29:10 CET 2012 classes.dex
```

This is the equivalent APK file build with a version of the Gradle Android plugin that has my small workaround/bugfix applied to its codebase:

```
ckesselh$ jar tvf build/distributions/helloandroid-1.0.0.apk 
  3171 Wed Dec 28 00:34:06 CET 2011 META-INF/MANIFEST.MF
  3292 Wed Dec 28 00:34:06 CET 2011 META-INF/ANDROIDD.SF
   776 Wed Dec 28 00:34:06 CET 2011 META-INF/ANDROIDD.RSA
   956 Wed Dec 28 00:34:06 CET 2011 res/layout/main.xml
  1268 Wed Dec 28 00:34:06 CET 2011 AndroidManifest.xml
  1012 Wed Dec 28 00:34:06 CET 2011 resources.arsc
3391652 Wed Dec 28 00:34:04 CET 2011 classes.dex
  3551 Wed Dec 28 00:34:06 CET 2011 clojure/data.clj
...
  3531 Wed Dec 28 00:34:06 CET 2011 clojure/test/tap.clj
    13 Wed Dec 28 00:34:06 CET 2011 clojure/version.properties
  4221 Wed Dec 28 00:34:06 CET 2011 clojure/walk.clj
 32066 Wed Dec 28 00:34:06 CET 2011 clojure/genclass.clj
... (many more) ...
```

I guess you can see the difference :-) (hint: the second version of the APK has all the non-Java resource files from the external JAR(s) embedded in its belly). Please bear in mind that there are similar differences in the APK's manifest file that I've left out here for the sake of brevity. Both the original Android ANT as well as the most recent Android Maven plugin will generate an APK similar to the second version when applied on the same project.

**Comment by fdasoghe** [comment] 2012-01-04 08:41
Thank you for your insightful analisys. Now it's clear to me, too :o)
You made a commit on your fork with a patch; could you create a pull request? I'll review it as soon as I can to merge into the main project (if nobody else come in before).

**Comment by ckesselh** [comment] 2012-01-04 08:48
My main concern with raising this issue was whether or not the approach taken by me is really the most versatile one and properly in-line with the fundamental design choices of the Gradle Android plugin. What do you think about the other options outlined in my earlier post?

**Comment by ealden** [comment] 2012-01-06 01:58
I think option 1 sounds good at this point, as it handles the situation (at least for Christian).  The two options are good as well, as they provide flexibility in behalf of the user, but I would like to see demand first before we have it as part of the release.

Christian, I think you can go ahead with a PR on what you have right now and I'll take a look as well.  I'll also have to recheck how the stock build.xml deals with this.

**Comment by ncjones** [comment] 2012-09-15 11:22
I have also encountered this issue. I have cherry-picked Christian's fix and created a pull request for it.

**Comment by slavasav** [comment] 2016-04-06 09:40
Have also run into this isue, guess it is not pulled  in still?

**Comment by ncjones** [comment] 2016-04-06 09:56
@slavasav this project is discontinued in favor of the official Android Gradle plugin. See https://developer.android.com/tools/building/plugin-for-gradle.html.

**Comment by slavasav** [comment] 2016-04-06 10:07
Yes, but it seems the problem is still there.

**Comment by fdasoghe** [comment] 2016-04-08 16:12
@slavasav What do you mean by "still there"? If the problem described here is present on the official Android Gradle plugin, you should talk about it on the official Android site (linked above by @ncjones ). If you're experiencing this problem because you're still using this project's plugin, it's discontinued and you should switch to the official one.
Closing this issue for being unattended.

**Closed as completed by fdasoghe** 2016-04-08 16:12 UTC
